### PR TITLE
Fix Haxe requirement

### PR DESCRIPTION
**Pull request by stilic**
People already successfully used the latest Haxe version with the latest commit of the FNF GitHub repository.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by stilic** [comment]
@AngelDTF can you check this

**Comment by AngelWyvern** [comment]
I would if I could test these changes myself, however I'm running out of storage space on my hard drive, and also my current Haxe configuration is working fine, so I'd rather not risk any issues by upgrading. I'll see if I can ask a friend later if they aren't busy.

**Comment by Trayfellow** [comment]
im using haxe 4.2.4 since psych pretty much needs it, although compiling on other stuff like this works just fine, just need to update your libraries

**Comment by Cheese-Curd** [comment]
just tried with 4.2.5, and couldn't even use git commands.

**Comment by AngelWyvern** [comment]
Was watching @Cheese-Curd's discord stream of her trying to set up the latest version of Haxe on a clean install of Windows 11. She is experiencing the same issues that are noted in the current README.md file, where gits are not working correctly. Therefore, I do not wish to update the readme and tell everyone to use latest when it has a bug that prevents users from even setting up Flixel itself.

**Comment by stilic** [comment]
> Was watching @Cheese-Curd's discord stream of her trying to set up the latest version of Haxe on a clean install of Windows 11. She is experiencing the same issues that are noted in the current README.md file, where gits are not working correctly. Therefore, I do not wish to update the readme and tell everyone to use latest when it has a bug that prevents users from even setting up Flixel itself.

this bug was fixed long time ago in new flixel ver.
also, can you give me the link for that stream? maybe it is outdated now.
i never got any issues with git itself just by using latest haxe and flixel versions on a original fnf source code compilation (i can even tell you psych engine users need the latest version of haxe. try compiling it and you will see).

**Comment by stilic** [comment]
> 

can you send a screenshot please? i need to see what's wrong so i can help you.

**Comment by AngelWyvern** [comment]
Sorry, I should've been more specific. I was watching her screen share while we were in a Discord call with each other, so it is not outdated. I saw it happen in real time, and the issue still occurs. It was not recorded on any websites, but if you really want to see, I could attempt contacting her and seeing if she would be willing to upload a video about this.

**Comment by Cheese-Curd** [comment]
I'd be fine recording this, however like Angel and I have said, it doesn't seem to work.

**Comment by Trayfellow** [comment]
> I'd be fine recording this, however like Angel and I have said, it doesn't seem to work.

this wont be good for people who are compiling psych first time

**Pull request closed without merging**
